### DISCUSSION TITLE
Allow admins to configure multiple allowed hosts

### DISCUSSION THREAD

**Discussion by neumantm** [pretix/pretix#2041] [Ideas]
Currently it seems, whenever a request is made, where the Host field is not the same as `SITE_URL`,which is the same as`[pretix] url` a 400 Bad Request is thrown.

This is the case even though the following lines exists in the settings:
`ALLOWED_HOSTS = ['*']`

I guess this is intentional?

I would prefer if admins could specify a list of allowed hosts.

**Comment by neumantm** [comment]
Currently I need this for monitoring my deployment using prometheus.
I have multiple instances of pretix and a load balancer.
The loadbalancer is reachable under my `SITE_URL`, but I want to monitor the individual pretix instances speratly of each other.
AFAIK, there is no feature in prometheus to override arbitrary HTTP headers or the HOST header, and therefore the HOST header is set to the IP of the container with the pretix instance, causing a 400.

**Reply by raphaelm** [reply]
Since you're talking about prometheus, I assume you're talking about the ``/metrics`` endpoint? If so, monitoring that separately won't make sense, it will always report the exact same numbers since it is served from a shared data source (redis). Separate checks would only make sense for uptime monitoring at ``/healthcheck/``.

**Reply by neumantm** [reply]
hm ok I see.
With healthcheck I had the same problem but fixed it using the following kubernetes config
```
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /healthcheck/
              port: 80
              httpHeaders:
                - name: Host
                  value: <my hostname>
```
