### DISCUSSION TITLE
docker-compose

### DISCUSSION THREAD

**Discussion by sonic182** [pretix/pretix#2653] [General]
Can you provide a docker-compose.yml for easily dev or prod deployment?

**Comment by pc-coholic** [comment]
We don't have an official or maintained docker-compose - but there is a few on GitHub that you can find. No guarantee on quality whatsoever though...

**Reply by sonic182** [reply]
Wow that was a fast respond!

**Comment by sonic182** [comment]
Yoy may accept a docker-compose contribution? into the repo?

**Reply by pc-coholic** [reply]
Absolutely! We're always open to contributions :-)

**Reply by raphaelm** [reply]
Probably not in the pretix repo right now. There is an empty repo pretix/docker-compose that accepts PRy, so far there has not been a fully recommendable version

**Comment by Zoz92** [comment]
Lo i try to make some docker-compose.yaml with some pretix.cfg 
Working so have fun, feel free to add the stack on the project

docker-compose.yaml

```
version: '3'

services:

  pretix:
    image: 'pretix/standalone:stable'
    container_name: pretix_app
    restart: always 
    depends_on:
      - db
      - redis
    volumes:
      - /home/hp590/Container_Prod/pretix/data:/data #/home/hp590/Container_Prod/ is my folder for all my prod container
      - /home/hp590/Container_Prod/pretix/conf:/etc/pretix /home/hp590/Container_Prod/ is my folder for all my prod container
    ports:
      - "8001:80" # my port 80 was already in use i choose 8001, feel free to pick your prefer port
    networks:
      - web
      - stack_network

  db:
    image: postgres:15.2-alpine
    container_name: db_pretix
    restart: always
    environment:
      - POSTGRES_USER=pretix
      - POSTGRES_PASSWORD=pick_a_strong_password_here
    volumes:
      - /home/hp590/Container_Prod/pretix/postgres:/var/lib/postgresql/data /home/hp590/Container_Prod/ is my folder for all my prod container
    networks:
      - stack_network
  
  redis:
    image: redis:latest
    container_name: redis_pretix
    restart: always
    networks:
      - stack_network

networks: 
  web:
    external: true
  stack_network:
    external: false
```

pretix.cfg
```
[pretix]
instance_name=pretix.your_fdn.org            
url=https://pretix.your.fdn.org            
currency=EUR
; DO NOT change the following value, it has to be set to the location of the
; directory *inside* the docker container
datadir=/data
registration=off

[locale]
default=fr 
timezone=Europe/Paris 

[database]
backend=postgresql_psycopg2
name=pretix
user=pretix
password=your_pick_a_strong_password_here_from_docker-compose.yaml
host=db

[mail]
from=FROM_MAIL
host=MAIL_SERVER
user=USERNAME
password=FOOBAR
port=587
tls=on
ssl=off

[redis]
location=redis://redis/0
; Remove the following line if you are unsure about your redis'security
; to reduce impact if redis gets compromised.
sessions=true

[celery]
backend=redis://redis/1
broker=redis://redis/2

```
