### DISCUSSION TITLE
Docker-Compose Instance is funky with all datepickers

### DISCUSSION THREAD

**Discussion by FabianSimonGross** [pretix/pretix#4103] [General]
So the following, I have a Docker Instance of Pretix-standalone with one Plugin installed running. The Problems I run into make no sense, like I enter a Date and Time and the time gets set from timezone Europe/Berlin to UTC so instead of 18:00 it changes to 20:00. I already dug around in all Settings, in the Database itself and also in redis everything is on timezone Europe/Berlin but the Data seems to get saved as UTC. 

Any Ideas how to fix it? I'm after two weeks of troubleshooting it myself at the end of my mental capacity and knowledge.

Here are all files I use to start it:

Dockerfile:
```
FROM pretix/standalone:latest
USER root
RUN pip install git+https://gitlab.fachschaften.org/kif/pretix-oidc.git
USER pretixuser
RUN cd /pretix/src && make production
```

Docker-Compose:
```
version: '3'

services:

  pretix:
    build: ./compile/
    restart: always
    depends_on:
      - db
      - redis
    volumes:
      - ./data:/data
      - ./conf:/etc/pretix
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sv-tickets.rule=Host(`tickets.studverthi.de`)"
      - "traefik.http.routers.sv-tickets.entrypoints=https"
      - "traefik.http.routers.sv-tickets.tls=true"
      - "traefik.http.routers.sv-tickets.tls.certresolver=le"
    networks:
      - web
      - stack_network

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=ticketing
      - POSTGRES_USER=ticketing
      - POSTGRES_PASSWORD=redacted
      - TZ=Europe/Berlin
    ports:
      - 5421:5432
    volumes:
      - ./pgsql:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - stack_network

  redis:
    image: redis:latest
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Berlin
    networks:
      - stack_network

networks:
  web:
    external: true
  stack_network:
    external: false
```

pretix.cfg
```
[pretix]
instance_name=tickets.example.com
url=https://tickets.example.com
currency=EUR
; DO NOT change the following value, it has to be set to the location of the
; directory *inside* the docker container
datadir=/data
registration=off
auth_backends=pretix_oidc.auth.OIDCAuthBackend

[locale]
default=de
timezone=Europe/Berlin

[database]
backend=postgresql
name=ticketing
user=ticketing
password=redacted
host=db

[oidc]
# label on the login button,
# default: Login with OpenID connect
title=SSO
# OIDC URIs, can generally be found unter .well-known/openid-configuration
# of your OIDC endpoint
issuer=https://sso.example.com/application/o/pretix/
authorization_endpoint=https://sso.example.com/application/o/authorize/
token_endpoint=https://sso.example.com/application/o/token/
userinfo_endpoint=https://sso.example.com/application/o/userinfo/
end_session_endpoint=https://sso.example.com/application/o/pretix/end-session/
jwks_uri=https://sso.example.com/application/o/pretix/jwks/
# OIDC client ID and secret
client_id=redacted
client_secret=redacted
# comma-separated list of scopes to request
# default: openid
# recommended: openid,email,profile
scopes=openid,email,profile
# what OIDC claim pretix should use to uniquely identify OIDC users
# default: sub
unique_attribute=entryUUID

[mail]
from=noreply@example.com
host=smtp.example.com
user=noreply@example.com
password=redacted
port=465
tls=on
ssl=off

[redis]
location=redis://redis/0
; Remove the following line if you are unsure about your redis'security
; to reduce impact if redis gets compromised.
sessions=true

[celery]
backend=redis://redis/1
broker=redis://redis/2
```
