### ISSUE TITLE
Getting error "Cannot connect to amqp://guest:**@127.0.0.1:5672//" in Docker on Pretix 4.4 image

### ISSUE THREAD

**Issue by DaVarga** [pretix/pretix#2300]
Hello guys, im getting following error when trying to run Pretix 4.4 in Docker.

```
[2021-11-09 08:17:13,908: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
2021-11-09T08:17:13.908844014Z Trying again in 2.00 seconds... (1/100)
```

**Describe the bug**
Despite supplying redis urls in the pretix.cfg Pretix tries to connect to an amqp server.

**Expected behavior**
Pretix connects to the supplied Redis url

**Additional context**
This might be related to a regession in Celery 4.4.7 https://github.com/celery/celery/issues/6370

**Steps to reproduce**
docker-compose.yml
```
version: '3.1'

services:

  postfix:
    image: boky/postfix
    volumes:
      - ./docker-volumes/postfix/keys:/etc/opendkim/keys
    ports:
      - "27017:27017"
    environment:
      ALLOWED_SENDER_DOMAINS: tix.example.com
      POSTFIX_myhostname: postfix-docker
      DKIM_AUTOGENERATE: true
    restart: on-failure

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: pretix
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pretix
      PGDATA: /data/postgres
    volumes:
      - ./docker-volumes/postgres:/data/postgres
    restart: on-failure

  redis:
    image: redis
    volumes:
      - ./docker-volumes/redis/config:/usr/local/etc/redis
    expose:
      - 6379
    restart: on-failure

  pretix:
    image: pretix/standalone:4.4
    volumes:
      - ./docker-volumes/pretix:/data
    ports:
      - "8345:80"
    restart: on-failure
    depends_on:
      - postgres
      - postfix
      - redis
```

pretix.cfg
```
[pretix]
instance_name=Test installation
url=https://localhost:8345
currency=EUR
datadir=/data
trust_x_forwarded_for=on
trust_x_forwarded_proto=on

[database]
backend=postgresql
name=pretix
user=pretix
password=password
host=postgres

[mail]
from=tickets@tix.example.com
host=postfix

[redis]
location=redis://redis:6379/1
sessions=false

[celery]
backend=redis://redis:6379/2
broker=redis://redis:6379/3

```
