### ISSUE TITLE
Stripe: Check if handling of "manual review" is correct

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#332]
If a payment has "elevated risk", stripe will trigger a "manual review". This apparently shows as a failed payment in pretix and if the user tries to pay again with a different card, two payments have been made.

The charge looks like this (only non-sensitice things shown):
```
object: "charge"
amount_refunded: 0
application: null
application_fee: null
captured: true
currency: "eur"
customer: null
description: null
destination: null
dispute: null
failure_code: null
failure_message: null
fraud_details: {}
invoice: null
livemode: true
metadata: {..}
outcome: {
    network_status: "approved_by_network"
    reason: "elevated_risk_level"
    risk_level: "elevated"
    seller_message: "Stripe evaluated this charge as having elevated risk, and placed it in your manual review queue."
    type: "manual_review"
paid: true
receipt_email: null
receipt_number: null
refunded: false
refunds:
    object: "list"
    data:
    has_more: false
    total_count: 0
    url: "/v1/charges/.../refunds"
review: "..."
shipping: null
source: ...
source_transfer: null
statement_descriptor: null
status: "succeeded"
```
