### ISSUE TITLE
Custom favicon not loading

### ISSUE THREAD

**Issue by C0NZZ** [pretix/pretix#3945]
### Problem and impact

When I set a custom favicon in the organizer shop design settings, it won't load. Instead, it answers with a 404.
It seems that instead of loading the icon from `https://<domain.com>/media/pub/<organizer>/favicon.ico.<stuff>.ico`, it tries to load from `https://<domain.com>/media/data/media/pub/<organizer>/favicon.ico.<stuff>.ico` (with *media/data/* before *media*). That, of course, doesn't work.
I see the icon uploaded in the /data/media/pub/<organizer> directory, as well as the custom css files (which do load correctly), so it is uploaded correctly, but the path that the shop tries to access it from is wrong.
This happens on the organizer page and on event shop pages from that organizer, with every organizer I create, and even if I spin up new instances of pretix.

### Steps to reproduce

It could be something with the docker compose volumes, maybe? My docker compose settings for pretix are here:
```
pretix:
    image: 'pretix/standalone:stable'
    container_name: pretix
    restart: always
    environment:
      - NUM_WORKERS=6
    depends_on:
      - db
      - redis
    ports:
      - 'XXXX:80'
    volumes:
      - ./data/pretix:/data
      - ./data/pretix.cfg:/etc/pretix/pretix.cfg
      - ./data/redis:/var/run/redis
    sysctls:
      - net.core.somaxconn=2048
    networks:
      - pretix
```

### Version

2024.2.0 (docker)
